#!/usr/bin/env bash
# AUTH=keys のとき、各ユーザーが置いたAPIキー（~/.config/dgx-qwen/api_key）を集めてTensorFoldのキーファイルを作る。
# イメージに含め、コンテナ tensorfold-keysync の中でrootとして動かす（/home は読み取り専用、/out はボリューム local-llm-keys）。
# ラベルはホームの持ち主のUnixユーザー名。10秒ごとに集め直し、内容が変わった時だけ置き換える。
# /out/revoked.txt に書いたユーザー名のキーは使わない。
set -u
out=/out/keys.txt
revoked=/out/revoked.txt

collect() {
  local home user f owner mode key
  echo "# generated by keysync.sh"
  for home in /home/*; do
    user="${home#/home/}"
    f="$home/.config/dgx-qwen/api_key"
    # 途中にリンクを含まない通常ファイルで、ホームの持ち主だけが読めるもの（600/400）に限る
    [[ -f $f && $(realpath -e "$f" 2>/dev/null) == "$f" ]] || continue
    read -r owner mode < <(stat -c '%u %a' "$f")
    [[ $owner == "$(stat -c %u "$home")" && $mode == [46]00 ]] || continue
    grep -qxF "$user" "$revoked" && continue
    key="$(head -n 1 "$f" | tr -d '\r')"
    [[ $key =~ ^[A-Za-z0-9_-]{20,128}$ ]] && echo "$user: $key"
  done
}

touch "$revoked"
while true; do
  tmp="$(mktemp /out/.keys.XXXXXX)"  # mktempは600で作る
  collect > "$tmp"
  if ! cmp -s "$tmp" "$out"; then
    mv "$tmp" "$out"
    echo "$(date '+%F %T') keys: $(grep -vc '^#' "$out")"
  fi
  rm -f "$tmp"
  sleep 10
done
