#!/bin/bash
# 各ユーザーが自分のホームに置いたAPIキー（~/.config/dgx-qwen/api_key）を集め、TensorFoldのキーファイルを作る。
# イメージに含め、コンテナ tensorfold-keysync の中で root として動かす（/home は読み取り専用、/out はボリューム local-llm-keys）。
# ラベルはホームの持ち主のUnixユーザー名。10秒ごとに集め直し、内容が変わった時だけ置き換える。
# /out/revoked.txt に書いたユーザー名のキーは使わない。
set -u
OUT=/out/keys.txt
REVOKED=/out/revoked.txt

collect() {
  echo "# generated by keysync.sh"
  for home in /home/*; do
    user=$(basename "$home")
    f="$home/.config/dgx-qwen/api_key"
    [ -f "$f" ] && [ ! -L "$f" ] || continue
    [ "$(realpath -e "$f" 2>/dev/null)" = "$f" ] || continue        # 途中のディレクトリがリンクなら無視
    [ "$(stat -c %u "$f")" = "$(stat -c %u "$home")" ] || continue  # ホームの持ち主のファイルだけ
    case "$(stat -c %a "$f")" in 600 | 400) ;; *) continue ;; esac  # 本人だけが読めるファイルだけ
    grep -qxF "$user" "$REVOKED" 2>/dev/null && continue
    key=$(head -n 1 "$f" | tr -d '\r')
    [[ "$key" =~ ^[A-Za-z0-9_-]{20,128}$ ]] || continue
    echo "$user: $key"
  done
}

touch "$REVOKED"
while true; do
  tmp=$(mktemp /out/.keys.XXXXXX)
  collect > "$tmp"
  if cmp -s "$tmp" "$OUT"; then
    rm -f "$tmp"
  else
    chmod 600 "$tmp" && mv "$tmp" "$OUT"
    echo "$(date '+%F %T') keys: $(grep -vc '^#' "$OUT")"
  fi
  sleep 10
done
